### ISSUE TITLE
background agent onboard command

### ISSUE THREAD

**Issue by jingkaihe** [jingkaihe/kodelet#75]
I'd like to have a `kodelet gha-agent-onboard` command.

The command line should accept the following options:

* `--github-app` which is default to `kodelet`
* `--auth-gateway-endpoint` which is default to `https://gha-auth-gateway.kodelet.com/api/github`

After `kodelet gha-agent-onboard` is run:

* Open `https://github.com/apps/${githubApp}` in the browser, and prompt user to install the app
* In the cli suggests "Press Enter to Continue once the app is installed"
* Check if the $ANTHROPIC_API_KEY exists in the current repo's github secret
   * If exist go to next step
   * if not, if the `ANTHROPIC_API_KEY` env var  does not exists, ask for anthropic key and run  `gh secret set ANTHROPIC_API_KEY --body the-key-enterred`
   *  if `ANTHROPIC_API_KEY` env var exists, prompt user whether they want to `gh secret set ANTHROPIC_API_KEY --body $ANTHROPIC_API_KEY`
* Upon installation, create a git branch `kodelet-background-agent-onboard-${unixtime}` and install the following into `./github/workflow/kodelet.yaml`:

```yaml
name: Background Kodelet

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

env:
  TIMEOUT_MINUTES: "300"

jobs:
  background-kodelet:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      issues: read
      pull-requests: read
      contents: read
    timeout-minutes: 15  # 15 Minutes
    if: |
      (
        (github.event_name == 'issues' && contains(github.event.issue.body, '@kodelet')) ||
        (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@kodelet')) ||
        (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@kodelet')) ||
        (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@kodelet'))
      ) &&
      (
        (github.event.issue.author_association == 'OWNER' || github.event.issue.author_association == 'MEMBER' || github.event.issue.author_association == 'COLLABORATOR') ||
        (github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'COLLABORATOR') ||
        (github.event.review.author_association == 'OWNER' || github.event.review.author_association == 'MEMBER' || github.event.review.author_association == 'COLLABORATOR')
      )

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Agent Environment
           run: |
             echo "YMMV"
      - name: Run Kodelet
        uses: jingkaihe/kodelet-action@v0.1.7-alpha
        with:
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          kodelet-config: |
            model: "claude-sonnet-4-0"
            weak_model: "claude-3-5-haiku-latest"
            max_tokens: 64000
            weak_model_max_tokens: 8192
            thinking_budget_tokens: 32000
```

* git commit with `git commit -sm "onboard kodelet background agent", create a pr with gh command
* display the pr link, and suggest once the PR is merged the gha based background agent will be up and running.
